# Generated by Django 4.2.6 on 2023-10-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='test@example.com', max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
